
fail_fast: false

repos:
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
        additional_dependencies: ['click==8.0.4']

-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        # additional_dependencies: [flake8-docstrings]
